### PR TITLE
Upgrade stripe version

### PR DESCRIPTION
**Pull request by duong-dsg**
Revert legacy Stripe plugin code.
Upgrade Stripe to version 11.3.
Replace deprecated functions with updated equivalents.

## Summary by Sourcery

Upgrade the Stripe integration to version 11.3, refactor the payment handling code to use the latest API features, and improve support for various payment methods.

Enhancements:
- Refactor the Stripe payment integration to use the latest API features and improve code readability.
- Update the Stripe payment method handling to support new payment methods and improve existing ones.

Build:
- Upgrade the Stripe library to version 11.3 in the project dependencies.

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Add missing tests same as in eventyay-tickets project.

**Review by mariobehling — CHANGES_REQUESTED** [review]
I am not sure why the payment options for SEPA Direct Debit, Affirm, Klarna, PayPal and Swish were removed. Please ensure these options continue to be available. Thanks!

**Comment by duong-dsg** [comment]
@mariobehling  The reason is that these methods are part of the recent update to Pretix, which comes with a new license. I removed them to avoid any potential licensing issues. Would you still like to use them?

**Comment by mariobehling** [comment]
When finished please add screenshots for changes and information on what to enter into the form elements, how to obtain this information and what settings need to be applied.

The goal of this issue was to upgrade the implementation. It looks like a few things are changed, e.g. instead of  the Stripe Connect Client ID, Secret key and Publishable key now a Webhook configuration is required. This seems to make the process more complex as the admin needs to create a webhook with specific permissions. The previous implementation as in the screenshot below is preferred.

Screenshot from 2024-12-18 04-50-20

**Comment by duong-dsg** [comment]
@mariobehling  May I have the permission to write into branch upgrade_stripe_version again? I can't push code to change for this PR. My account is nttduong1@tma.com.vn

**Comment by mariobehling** [comment]
I do not recommend to share email addresses on public Github resources.

Please make a PR from your personal fork.

Please follow our development practices as outlined here https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by duong-dsg** [comment]
Thanks for the reminder. The PR may have been created while it was still private. I will resubmit another PR and attach instructions for generating a Stripe key.

**Pull request closed without merging**
